export {default as Tarif} from './luarNegeri/tarif/Tarif'
export {default as CalonAgen} from './calonAgen/agen/CalonAgen'
export {default as OmzetLuarNegri} from './dashboard/omzetLuarNegri/OmzetLuarNegri'
export {default as OmzetDomestik} from './dashboard/omzetDomestik/OmzetDomestik'
export {default as Member} from './calonAgen/member/Member'
export {default as Home} from './home/Home'
export {default as BookingPage} from './luarNegeri/booking/BookingPage'
export {default as Auth} from './auth/Auth'
