export {default as Tarif} from './luarNegeri/tarif/Tarif';
export {default as CalonAgen} from './calonAgen/agen/CalonAgen';
export {default as OmzetLuarNegri} from './dashboard/omzetLuarNegri/OmzetLuarNegri';
export {default as OmzetDomestik} from './dashboard/omzetDomestik/OmzetDomestik';
export {default as Member} from './calonAgen/member/Member';
export {default as Home} from './home/Home';
export {default as BookingPage} from './luarNegeri/booking/BookingPage';
export {default as Login} from './auth/Login';
export {default as TransaksiLuarNegeri} from './luarNegeri/transaksi/TransaksiLuarNegeri';
export {default as Tracking} from './luarNegeri/tracking/Tracking';
export {default as DomestikTransaksi} from './Domestik/DomestikTransaksi';
export {default as ScanBarcode} from './luarNegeri/scanBarcode/ScanBarcode';
export {default as PengaturanHome} from './pengaturan/PengaturanHome';
export {default as DataPengguna} from './pengaturan/masterData/DataPengguna'
